feat(dotbot): verify if dotbot configs exists before running
  ## what
  - Verify if a dotbot config exists before running the config.
  - If the config file doesn't exist, exit after checking the other
    config arguments.
    - Ex: ./install-standalone astronvi nvm
      - Will flag 'astronvi' doesn't exist and exit after checking 'nvm'
  - Checks even if the config has a suffix of '-sudo'
    - '-sudo' is ignored to find the config file

  ## how

  ## why
  - Better to check if all the config files exist before running them
  - Easier to debug if a problem occurs

  ## where

  ## usage

diff --git a/install-standalone b/install-standalone
--- a/install-standalone
+++ b/install-standalone
@@ -42,6 +42,42 @@ git submodule update --init --recursive
 # load XDG dotfile locations. https://wiki.archlinux.org/title/XDG_Base_Directory
 source tools/zsh/.zshenv
 
+# ------------------------------------------------------------------------------------------------ #
+# Verify dotbot config files exist.
+# Also checks if the config file exists if it has a suffix of '-sudo'. Ex: apt-sudo
+# Checks if the file exists in meta/configs/ folder
+
+sudoSuffix="-sudo"
+exitIfConfigNotFound=false    # used as a flag to exit IF a config file is NOT found
+for config in ${@}; do
+  # remove suffix '-sudo' in the variable $config
+  # check if the config filepath doesn't exist
+  #   print message
+  #   flag variable to exit
+
+  # remove suffix '-sudo'
+  # obtained from https://stackoverflow.com/a/16623897/3053548
+  config=${config%"$sudoSuffix"}
+  configFilepath="${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
+  if [[ ! -e $configFilepath ]]; then
+    echo -e "Dotbot config \\033[1;31m$configFilepath \\033[0mDOESN'T exists"
+
+    exitIfConfigNotFound=true
+  fi
+done
+
+# exit if a config filepath is NOT found
+if [[ $exitIfConfigNotFound == true ]]; then
+  echo -e "\nexiting"
+  exit 1
+fi
+
+# cleanup variables
+unset sudoSuffix
+unset exitIfConfigNotFound
+
+# ------------------------------------------------------------------------------------------------ #
+
 for config in ${@}; do
   # create temporary file
   configFile="$(mktemp)"
